version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres 
    ports:
      - "5433:5432"
    networks:
      - my_network

networks:
   my_network:
      driver: bridge
      ipam:
        config:
          - subnet: 192.168.4.0/24
